variables:
  GIT_SUBMODULE_STRATEGY: recursive
  NIXQC_SRCURL: http://kashyyyk:8888/nix-src
  NIXQC_AVX: 0
  NIXPKGS_ALLOW_UNFREE: 1

stages:
  - build
  - test
  - distribute

before_script:
  - mkdir -p ~/.config/nix
  - echo "experimental-features = nix-command flakes" > ~/.config/nix/nix.conf
  - nix-env -f ./nix/pkgs.nix -iA bash cachix

nix build:
  stage: build
  tags:
    - nix
  script:
    - |
      nix-build -E "(import ./nix/pkgs.nix).python3.pkgs.pysisyphus.overrideAttrs (oldAttrs: {
        doCheck = false;
        doInstallCheck = false;
      })"
  after_script:
    - |
      if [ -n "$CACHIX_AUTH_TOKEN" ]; then
        realpath result | cachix push pysisyphus
      fi


nix shell:
  stage: build
  tags:
    - nix
  script:
    - nix develop --command echo ""
  after_script:
    - |
      if [ -n "$CACHIX_AUTH_TOKEN" ]; then
        nix develop --profile pysis-profile && cachix push pysisyphus pysis-profile
      fi

nix test:
  stage: test
  tags:
    - nix
    - turbomole
    - orca
    - gamess
  script:
    - |
      nix-build -E "(import ./nix/pkgs.nix).python3.pkgs.pysisyphus.override {
        enableOrca = true;
        enableTurbomole = true;
        enableGamess = true;
        enableMultiwfn = true;
      }"

#container:
  #stage: distribute
  #tags:
    #- nix
  #before_script:
    #- unset NIXPKGS_ALLOW_UNFREE
  #script:
    #- nix-build ./nix/container.nix
  #after_script:
    #- cp result pysisyphus.tar.gz
    #- cp result-2 pysisyphus.sif
  #artifacts:
    #paths:
      #- pysisyphus.tar.gz
      #- pysisyphus.sif
