name: Python application

on:
    push:
        paths-ignore:
            - "docs/**"
            - "examples/**"
            - "tests_staging/**"
            - "deprecated/**"
            - "scripts/**"
    workflow_dispatch:
jobs:
  build:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v2
    - name: Build with Nix and run tests
      run: |
        nix-build --arg fullTest false
